---
version: '3.7'

services:
  nexus3:
    image: sonatype/nexus3:3.36.0
    init: true
    container_name: nexus3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_network
    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - "traefik.http.services.nexus3-secure.loadbalancer.server.port=8081"
      - "traefik.http.routers.nexus3-secure.service=nexus3-secure"
      - "traefik.http.routers.nexus3-secure.tls.certresolver=gandi-cr"
      - "traefik.http.routers.nexus3-secure.entrypoints=https,https_priv"
      - "traefik.http.routers.nexus3-secure.rule=Host(`nexus3.${TRAEFIK_HOST}`)|| Host(`nexus3.${TRAEFIK_HOST_VPC}`)"
      - "traefik.http.services.nexus3-dockerhub.loadbalancer.server.port=8082"
      - "traefik.http.routers.nexus3-dockerhub.service=nexus3-dockerhub"
      - "traefik.http.routers.nexus3-dockerhub.tls.certresolver=gandi-cr"
      - "traefik.http.routers.nexus3-dockerhub.entrypoints=https,https_priv"
      - "traefik.http.routers.nexus3-dockerhub.rule=Host(`hub.docker.nexus3.${TRAEFIK_HOST}`) || Host(`hub.docker.nexus3.${TRAEFIK_HOST_VPC}`)"
      - "traefik.http.services.nexus3-dockerpush.loadbalancer.server.port=8083"
      - "traefik.http.routers.nexus3-dockerpush.service=nexus3-dockerpush"
      - "traefik.http.routers.nexus3-dockerpush.entrypoints=https_priv"
      - "traefik.http.routers.nexus3-dockerpush.rule=Host(`push.docker.nexus3.${TRAEFIK_HOST_VPC}`)"
      - "traefik.http.services.nexus3-dockerplatypuspull.loadbalancer.server.port=8083"
        # - 'traefik.http.middlewares.platypuspull-auth.forwardauth.address=https://get.linkurio.us/api/auth/login'
      - 'traefik.http.middlewares.platypuspull-auth.forwardauth.address=https://get.linkurio.us/'
      - 'traefik.http.middlewares.platypuspull-auth-headers.headers.customrequestheaders.Authorization=Basic BASE64-VALUE'
      - "traefik.http.routers.nexus3-dockerplatypuspull.middlewares=platypuspull-auth,platypuspull-auth-headers"
      - "traefik.http.routers.nexus3-dockerplatypuspull.service=nexus3-dockerpush"
      - "traefik.http.routers.nexus3-dockerplatypuspull.entrypoints=https_priv"
      - "traefik.http.routers.nexus3-dockerplatypuspull.rule=Host(`ppull.nexus3.${TRAEFIK_HOST_VPC}`)"

networks:
  traefik_network:
    external: true
