---
version: '3.7'

services:
  nexus3:
    image: sonatype/nexus3:3.22.0
    init: true
    container_name: nexus3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - 8081:8081

volumes:
    nexus-data: {}
