---
version: '3.7'

services:
  nexus3:
    image: sonatype/nexus3:3.22.0
    init: true
    container_name: nexus3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - "nexus-data:/nexus-data"
    networks:
      - traefik_network
    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - "traefik.http.services.nexus3-secure.loadbalancer.server.port=8081"
      - "traefik.http.routers.nexus3-secure.entrypoints=https"
      - "traefik.http.routers.nexus3-secure.rule=Host(`nexus3.${TRAEFIK_HOST}`)"

volumes:
  nexus-data: {}

networks:
  traefik_network:
    external: true
